#include <iostream>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <cfloat>
#include <ciso646>
#include <climits>
#include <clocale>
#include <cmath>
#include <csetjmp>
#include "gameserver.hpp"
#include "gamestate.hpp"
#include "resourcemanager.hpp"